package com.example.ui

object LanguageHelper {
    private val translations = mapOf(
        "app_title" to Pair("NexAttendance", "নেক্সঅ্যাটেনডেন্স"),
        "tagline" to Pair("Digital Attendance Register for Schools", "বিদ্যালয়ের ডিজিটাল হাজিরা খাতা"),
        "loading" to Pair("Loading system, please wait...", "সিস্টেম লোড হচ্ছে, অনুগ্রহ করে অপেক্ষা করুন..."),
        "get_started" to Pair("Get Started", "শুরু করুন"),
        "login" to Pair("Login", "লগইন"),
        "restore_backup" to Pair("Restore Backup", "ব্যাকআপ রিস্টোর করুন"),
        "language_label" to Pair("Language / ভাষা", "ভাষা / Language"),
        "school_setup" to Pair("School Setup", "স্কুল সেটআপ"),
        "school_logo" to Pair("School Logo / Emblem", "স্কুলের লোগো / প্রতীক"),
        "school_name" to Pair("School Name", "স্কুলের নাম"),
        "school_name_req" to Pair("School name is required", "স্কুলের নাম আবশ্যিক"),
        "eiin" to Pair("EIIN (Optional)", "EIIN (ঐচ্ছিক)"),
        "school_code" to Pair("School Code", "স্কুল কোড"),
        "school_type" to Pair("School Type", "স্কুলের ধরন"),
        "address" to Pair("Address", "ঠিকানা"),
        "phone" to Pair("Phone Number", "ফোন নম্বর"),
        "email" to Pair("Email Address", "ইমেইল ঠিকানা"),
        "website" to Pair("Website URL", "ওয়েবসাইট"),
        "principal_name" to Pair("Principal / Headmaster Name", "অধ্যক্ষ / প্রধান শিক্ষকের নাম"),
        "academic_start" to Pair("Academic Year Start", "শিক্ষাবর্ষ শুরুর তারিখ"),
        "academic_end" to Pair("Academic Year End", "শিক্ষাবর্ষ শেষের তারিখ"),
        "save_setup" to Pair("Save & Complete Setup", "সংরক্ষণ ও সেটআপ সম্পন্ন করুন"),
        "save_success" to Pair("Successfully saved!", "সফলভাবে সংরক্ষিত হয়েছে!"),
        "role_select" to Pair("Choose Your Role", "আপনার রোল নির্বাচন করুন"),
        "role_admin" to Pair("Administrator (Full Access)", "অ্যাডমিনিস্ট্রেটর (পূর্ণ অ্যাক্সেস)"),
        "role_principal" to Pair("Principal / Head (Reports & Viewer)", "অধ্যক্ষ (রিপোর্ট ও ভিউয়ার)"),
        "role_teacher" to Pair("Teacher (Manage Attendance)", "শিক্ষক (হাজিরা পরিচালনা)"),
        "role_staff" to Pair("Office Staff (Data Entry)", "অফিস স্টাফ (ডাটা এন্ট্রি)"),
        "dashboard" to Pair("Dashboard", "ড্যাশবোর্ড"),
        "total_students" to Pair("Total Students", "মোট শিক্ষার্থী"),
        "present_today" to Pair("Present Today", "আজ উপস্থিত"),
        "absent_today" to Pair("Absent Today", "আজ অনুপস্থিত"),
        "late" to Pair("Late", "দেরি (বিলম্ব)"),
        "leave" to Pair("On Leave", "ছুটিতে"),
        "total_classes" to Pair("Total Classes", "মোট ক্লাস"),
        "total_sections" to Pair("Total Sections", "মোট সেকশন"),
        "attendance_rate" to Pair("Attendance Rate", "উপস্থিতির হার"),
        "recent_logs" to Pair("Recent Attendance Logs", "সাম্প্রতিক হাজিরা খতিয়ান"),
        "take_attendance" to Pair("Take Attendance", "হাজিরা নিন"),
        "academic_year" to Pair("Academic Year", "শিক্ষাবর্ষ"),
        "class" to Pair("Class", "ক্লাস"),
        "section" to Pair("Section", "সেকশন"),
        "month" to Pair("Month", "মাস"),
        "day" to Pair("Day / Date", "দিন / তারিখ"),
        "submit_attendance" to Pair("Submit Attendance", "হাজিরা সংরক্ষণ করুন"),
        "attendance_saved" to Pair("Attendance saved successfully!", "হাজিরা সফলভাবে সংরক্ষিত হয়েছে!"),
        "status_p" to Pair("Present", "উপস্থিত"),
        "status_a" to Pair("Absent", "অনুপস্থিত"),
        "status_l" to Pair("Late", "বিলম্ব"),
        "status_lv" to Pair("Leave", "ছুটি"),
        "status_h" to Pair("Holiday", "ছুটির দিন"),
        "monthly_register" to Pair("Monthly Attendance Register", "মাসিক হাজিরা রেজিস্টার"),
        "search_students" to Pair("Search Students", "শিক্ষার্থী খুঁজুন"),
        "search_placeholder" to Pair("Search by Name, Roll, ID or Phone", "নাম, রোল, আইডি বা মোবাইল লিখে খুঁজুন"),
        "student_profile" to Pair("Student Profile", "শিক্ষার্থীর প্রোফাইল"),
        "student_id" to Pair("Student ID", "শিক্ষার্থী আইডি"),
        "roll_number" to Pair("Roll Number", "রোল নম্বর"),
        "guardian_phone" to Pair("Guardian Phone", "অভিভাবকের ফোন"),
        "father_name" to Pair("Father's Name", "বাবার নাম"),
        "mother_name" to Pair("Mother's Name", "মায়ের নাম"),
        "dob" to Pair("Date of Birth", "জন্ম তারিখ"),
        "gender" to Pair("Gender", "লিঙ্গ"),
        "blood_group" to Pair("Blood Group", "রক্তের গ্রুপ"),
        "attendance_history" to Pair("Attendance History", "হাজিরা ইতিহাস"),
        "reports" to Pair("Reports & Printing", "রিপোর্ট ও প্রিন্টিং"),
        "report_daily" to Pair("Daily Report", "দৈনিক রিপোর্ট"),
        "report_weekly" to Pair("Weekly Report", "সাপ্তাহিক রিপোর্ট"),
        "report_monthly" to Pair("Monthly Register", "মাসিক রেজিস্টার"),
        "report_yearly" to Pair("Yearly Report", "বার্ষিক রিপোর্ট"),
        "report_student" to Pair("Student-wise Report", "শিক্ষার্থী-ভিত্তিক রিপোর্ট"),
        "report_class" to Pair("Class-wise Report", "ক্লাস-ভিত্তিক রিপোর্ট"),
        "report_section" to Pair("Section-wise Report", "সেকশন-ভিত্তিক রিপোর্ট"),
        "report_summary" to Pair("School Summary", "স্কুলের সারসংক্ষেপ"),
        "analytics" to Pair("Analytics & Trends", "বিশ্লেষণ ও প্রবণতা"),
        "print_view" to Pair("Print Register (A4 Landscape)", "প্রিন্ট রেজিস্টার (A4 ল্যান্ডস্কেপ)"),
        "backup_restore" to Pair("Backup & Restore", "ব্যাকআপ এবং রিস্টোর"),
        "local_backup" to Pair("Create Local Backup", "লোকাল ব্যাকআপ তৈরি করুন"),
        "restore_now" to Pair("Restore DB Now", "ডাটাবেস রিস্টোর করুন"),
        "cloud_backup" to Pair("Google Drive Backup (Cloud Sync)", "গুগল ড্রাইভ ব্যাকআপ (ক্লাউড সিঙ্ক)"),
        "tools_settings" to Pair("Smart Tools & Simulators", "স্মার্ট টুলস এবং সিমুলেটর"),
        "generate_demo_btn" to Pair("Generate 100 Demo Students & Logs", "১০০ জন ডেমো শিক্ষার্থী এবং হাজিরা তৈরি করুন"),
        "generate_demo_desc" to Pair("Pre-populates classes, sections, students, and full history for June & July 2026 to preview registers, reports, and charts instantly.", "শ্রেণী, সেকশন, শিক্ষার্থী এবং জুন ও জুলাই ২০২৬ এর হাজিরা খাতা স্বয়ংক্রিয়ভাবে তৈরি করুন যাতে চার্ট ও রিপোর্ট পরীক্ষা করতে পারেন।"),
        "demo_success" to Pair("Demo data generated successfully!", "ডেমো ডাটা সফলভাবে তৈরি হয়েছে!"),
        "low_attendance" to Pair("Low Attendance Risk Students (<80%)", "কম উপস্থিতির ঝুঁকিপূর্ণ শিক্ষার্থী (<৮০%)"),
        "sim_qr" to Pair("QR Code Scanner Simulator", "কিউআর কোড স্ক্যানার সিমুলেটর"),
        "sim_rfid" to Pair("RFID/NFC Smart Card Tap Simulator", "আরএফআইডি কার্ড ট্যাপ সিমুলেটর"),
        "sim_finger" to Pair("Biometric Fingerprint Scanner Simulator", "ফিঙ্গারপ্রিন্ট স্ক্যানার সিমুলেটর"),
        "welcome" to Pair("Welcome", "স্বাগতম"),
        "no_students" to Pair("No students found. Go to Setup or generate Demo Data.", "কোনো শিক্ষার্থী পাওয়া যায়নি। সেটআপ করুন বা ডেমো ডাটা তৈরি করুন।"),
        "add_student" to Pair("Add New Student", "নতুন শিক্ষার্থী যোগ করুন"),
        "add_class" to Pair("Add Class", "ক্লাস যোগ করুন"),
        "add_section" to Pair("Add Section", "সেকশন যোগ করুন"),
        "manage_classes" to Pair("Manage Classes & Sections", "ক্লাস ও সেকশন পরিচালনা"),
        "user_role" to Pair("Logged in as", "লগইন রোল"),
        "change_role" to Pair("Change Role", "রোল পরিবর্তন করুন"),
        "sim_attendance" to Pair("Simulate Scan Check-in", "স্ক্যান করে হাজিরা দিন"),
        "sim_success" to Pair("Attendance checked in successfully via scanner!", "স্ক্যানারের মাধ্যমে হাজিরা সফলভাবে সম্পন্ন হয়েছে!"),
        "print_sheet" to Pair("A4 Print Sheet View", "A4 প্রিন্ট শীট ভিউ"),
        "print" to Pair("Print / Share PDF", "প্রিন্ট / পিডিএফ শেয়ার করুন"),
        "guardian_msg" to Pair("Guardian SMS Warning", "অভিভাবক এসএমএস সতর্কবার্তা"),
        "guardian_sms_desc" to Pair("Automatically drafting absent SMS notifications for guardians.", "অনুপস্থিত শিক্ষার্থীদের অভিভাবকদের জন্য খসড়া এসএমএস বার্তা।")
    )

    fun translate(key: String, isBengali: Boolean): String {
        val pair = translations[key] ?: return key
        return if (isBengali) pair.second else pair.first
    }
}
